HW3_1/Models/Contacts.cs
using System.ComponentModel.DataAnnotations;

namespace HW3_1.Models
{
    public class Contacts
    {
        [Display(Name = "id")]
        [Required(ErrorMessage = "Id не установлен")]
        public int Id { get; set; }
        [Display(Name = "название")]
        [Required(ErrorMessage = "название не установлен")]
        public string Title { get; set; }
        [Display(Name = "сообщение")]
        [Required(ErrorMessage = "сообщение не установлен")]
        public string Message { get; set; }

    }
}

HW3_1/Models/ErrorViewModel.cs
namespace HW3_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HW3_1/Controllers/ContactsController.cs
using HW3_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace HW3_1.Controllers
{
    public class ContactsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public JsonResult Check(Contacts model)
        {
            if (ModelState.IsValid)
            {
                return Json(new { success = true, data = model });
            }
            else
            {
                return Json(new { success = false });
            }
        }
    }
}

HW3_1/Controllers/HomeController.cs
using HW3_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HW3_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HW3_1/Views/Contacts/Index.cshtml
@model Contacts
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Aboba </h1>

<div class="form-contacts">
    <form id="contactForm" method="post" asp-controller="Contacts" asp-action="Check">
        <label asp-for="Id"></label>
        <input asp-for="Id" />
        <span asp-validation-for="Id"></span>

        <label asp-for="Title"></label>
        <input asp-for="Title" />
        <span asp-validation-for="Title"></span>

        <label asp-for="Message"></label>
        <input asp-for="Message" />
        <span asp-validation-for="Message"></span>
        <input type="button" id="submitForm" value="отправить"></input>
    </form>
    
    <div class="test_table">

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>

        $(document).ready(function () {
            
            $('#submitForm').click(function () {
                var formData = $('#contactForm').serialize();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Check", "Contacts")',
                    data: formData,
                    success: function (response) {
                        console.log(response.data);
                        if (response.success) {
                            $('.test_table').append('<div>' + response.data.title + ': ' + response.data.message + '</div>');
                        } 
                        else 
                        {
                            alert('Ошибка: Некорректные данные');
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error("Status: " + status);
                        console.error("Error: " + error);
                        alert('Произошла ошибка при отправке данных: ' + xhr.responseText);
                    }
                });
            });
        });
    </script>
</div>

HW3_1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HW3_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HW3_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HW3_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HW3_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HW3_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>